### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by nilegard** [jyruzicka/kanban#2]
Hi,

I'm having problem running this app as I always get an uncaught exception:

[OmniFocusApplication defaultDocument]: unrecognized selector sent to instance 0x7ff7b0c72390
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OmniFocusApplication defaultDocument]: unrecognized selector sent to instance 0x7ff7b0c72390'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00007fff9026425c **exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff8ff75e75 objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff9026712d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x00007fff901c2322 ___forwarding_** + 1010
    4   CoreFoundation                      0x00007fff901c1ea8 _CF_forwarding_prep_0 + 120
    5   kanban-fetch                        0x000000010d4a757c +[JROmniFocus projects] + 76
    6   kanban-fetch                        0x000000010d4a6c7f main + 303
    7   libdyld.dylib                       0x00007fff908b75fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

I tried running the app with different DBPATH but I always get the same exception.
Would really appreciate some help or tips on how to resolve this. 
I'm using Omnifocus 2 and downloaded the corresponding binary (http://1klb.com/apps/kanban-fetch-OF2.zip). 

Regards,

Nilegard

**Comment by jyruzicka** [comment]
Hi nilegard, thanks for the interest. Sounds like this is actually an issue for [kanban-fetch](https://github.com/jyruzicka/kanban-fetch). I'm busily updating this and making it more user-friendly - I'd be interested to know if V1.1.3 fixes things for you.

(If you're downloading the binary from the website, it might not be up-to-date _quite_ yet: that's my next project for today. If the link in kanban-fetch's readme leads to a 404, it's not up-to-date yet!)

[ETA: I'll close this issue - if you keep getting these problems, open an issue in kanban-fetch and I'll look into it!]

**Comment by nilegard** [comment]
Thank you! 
I suspected that I needed the Pro version of Omnifocus2 and your debug message confirmed that.
Upgraded and it works like a charm now. Kudos!
