### ISSUE TITLE
Any chance to get the arrows back (between folders/parent projects) instead of the pipe "|"

### ISSUE THREAD

**Issue by naupaka** [jyruzicka/kanban#3]
Thanks for all the hard work on 2.0.  I miss the arrows! I tried digging through the code to find where to change it myself, but I don't know ruby so I figured it would be better not to break anything.

**Comment by naupaka** [comment]
There used to be a place where the delimiter was defined in projects.rb, but it's gone now as far as I can tell?

**Comment by naupaka** [comment]
Nevermind, I figured it out.  Added a .gsub in _folder.haml and now I have a sweet custom arrow delimiter.

`%h3.parent-title{class: folder.css_classes}=folder.name.gsub('|',' &#10142; ')`

**Comment by jyruzicka** [comment]
:+1: 

I'll chuck this into the config file in the next couple of days, but your solution is pretty much exactly what I was going to suggest.
